# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BhuBhawma
                                 A QGIS plugin
 Help to calculate the different gravity anomalies like bouguer anomaly
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-11-09
        copyright            : (C) 2018 by Jeevan U
        email                : jeevanthanal@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Jeevan U'
__date__ = '2018-11-09'
__copyright__ = '(C) 2018 by Jeevan U'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BhuBhawma class from file BhuBhawma.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bhu_bhawma import BhuBhawmaPlugin
    return BhuBhawmaPlugin()
